### BOILER PLATE ###
- name: Creates remote docker projects directory
  ansible.builtin.file:
    path: '{{docker_dir}}'
    state: directory

- name: Update local docker directory name variable
  ansible.builtin.set_fact:
    stack_dir: "{{ [docker_dir, project_name] | join('/') }}"

- name: Creates remote project directory
  ansible.builtin.file:
    path: '{{stack_dir}}'
    state: directory

- name: Transfer and convert the docker compose jinja2 template
  ansible.builtin.template:
    src: "compose.yml"
    dest: "{{stack_dir}}/compose.yml"

### MAIN ###
- name: Creates remote project directory
  ansible.builtin.file:
    path: '{{stack_dir}}/traefik/data'
    state: directory

- name: Copy a file to a remote loc (and render if template)
  ansible.builtin.template:
    src: "traefik_dynamic.yml"
    dest: "{{stack_dir}}/traefik/data/traefik_dynamic.yml"

- name: Copy a file to a remote loc (and render if template)
  ansible.builtin.copy:
    src: "traefik_static.yml"
    dest: "{{stack_dir}}/traefik/data/traefik_static.yml"

### HANDLE SECRETS WORK ###

- name: Create .env file with traefik dashboard credentials
  ansible.builtin.copy:
    dest: "{{stack_dir}}/.env"
    content: |
      TRAEFIK_DASHBOARD_CREDENTIALS={{ TRAEFIK_DASHBOARD_CREDENTIALS }}

- name: Create api_token file
  ansible.builtin.copy:
    content: "{{ desec_api_token }}"
    dest: "{{stack_dir}}/desec_api_token.txt"

- name: Create acme.json file
  ansible.builtin.file:
    path: "{{stack_dir}}/traefik/data/acme.json"
    state: "touch"
    mode: '0600'

### HANDLE NETWORKING ###

- name: Create shared networks
  community.docker.docker_network:
    name: "{{ item.name }}"
    ipam_config: "{{ item.ipam_options }}"
  loop: "{{ networks.shared | default([], true) }}"
  when: networks.shared is not none
  

- name: Create traefik specific networks
  community.docker.docker_network:
    name: "{{ item.name }}"
    ipam_config: "{{ item.ipam_options }}"
  loop: "{{ networks.traefik_specific | default([], true) }}"
  when: networks.traefik_specific is not none

### DEPLOY ###
- name: Deploy Docker Compose Stack
  community.docker.docker_compose_v2:
    project_name: '{{project_name}}'
    project_src: '{{stack_dir}}'
    files:
    - compose.yml


