
host_docker_dir: "/home/ansible/docker"

### NETWORK CENTER ###

host_networks:
  traefik_specific: # these containers don't have Tailscale DNS and connection-ability
  # nginx_file_server
    - name: "{{nginx_file_server.network_backend.name}}"
      ipam_options: "{{nginx_file_server.network_backend.ipam_options}}"
      traefik_ip: "{{nginx_file_server.network_backend.traefik_ips.traefik}}"
  # public_network_center
    - name: "{{public_network_center.network_backend.name}}"
      ipam_options: "{{public_network_center.network_backend.ipam_options}}"
      traefik_ip: "{{public_network_center.network_backend.traefik_ips.traefik}}"
### TRAEFIK SERVICE SPECIFIC VARS ###

public_network_center:
  network_backend:
    name: "public_tailscale"
    ipam_options:
    - subnet: "10.100.0.0/29"
      gateway: "10.100.0.1"
    traefik_ips:
      traefik: "10.100.0.2"
  traefik_domain: "traefik.webvm.wiresndreams.dev"

# domains for ssl
# remember to setup CAA and A records
host_public_domains:
- "dev.wiresndreams.dev"
- "dev.blog.wiresndreams.dev"
- "dev.homelab.wiresndreams.dev"
# - "dev.tools.homelab.wiresndreams.dev"


### NGINX SERVICE SPECIFIC VARS ###

nginx_file_server:
  name: "nginx_file_server"
  network_backend:
    name: "t3_nginx"
    ipam_options:
    - subnet: "10.100.32.0/29"
      gateway: "10.100.32.1"
    traefik_ips:
      traefik: "10.100.32.2"
      nginx: "10.100.32.3"

# host_site_path_in_repo: "site-build"

site_location: "/var/www/html"

host_site_paths:
- "main"
- "blog"
- "homelab"
# - "homelab-tools"
