myhosts:
  hosts:
    webvm:
        ansible_host: 100.84.38.22
        ansible_become: yes
        ansible_become_method: sudo
        ansible_connection: ssh
        ansible_user: root
        # ansible_python_interpreter: "/usr/bin/python3.11"