### BOILER PLATE ###
- name: Creates remote docker projects directory
  ansible.builtin.file:
    path: '{{docker_dir}}'
    state: directory

- name: Update local docker directory name variable
  ansible.builtin.set_fact:
    stack_dir: "{{ [docker_dir, project_name] | join('/') }}"

- name: Creates remote project directory
  ansible.builtin.file:
    path: '{{stack_dir}}'
    state: directory

- name: Transfer and convert the docker compose jinja2 template
  ansible.builtin.template:
    src: "compose.yml"
    dest: "{{stack_dir}}/compose.yml"

### MAIN ###
- name: Copy a file to a remote loc (and render if template)
  ansible.builtin.template:
    src: "nginx.conf"
    dest: "{{stack_dir}}/nginx.conf"

- name: copying files with playbook
  become: true 
  copy:
    src: "../../site-build/{{ item }}"
    dest: "{{site_location}}/"
  loop: "{{ site_paths }}"

### DEPLOY ###
- name: Deploy Docker Compose Stack
  community.docker.docker_compose_v2:
    project_name: '{{project_name}}'
    project_src: '{{stack_dir}}'
    files:
    - compose.yml


